version: '3.1'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kanjimap
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
        #    ports:
        #      - 3306:3306
  app:
    image: golang:1.22.3-bookworm
    restart: always
    environment:
      SECRET_KEY: hello
    ports:
      - 8080:8080
    volumes:
      - ./vue:/vue
      - ./go:/go
    command: ["/usr/local/go/bin/go", "run", "/go/main.go"] 
      #command: ["tail", "-f", "/dev/null"]


      
